### ISSUE TITLE
`transmute_copy` should not have alignment requirements 

### ISSUE THREAD

**Issue by arielb1** [nikomatsakis/rust-memory-model#14]
`std::mem::transmute_copy` should work on unaligned pointers, unlike dereferences and `ptr::read`.

**Comment by Amanieu** [comment]
cc https://github.com/rust-lang/rfcs/issues/1703

**Comment by newpavlov** [comment]
This issue is fixed, see the referenced issue.

**Comment by RalfJung** [comment]
It turns out indeed that `transmute_copy` uses `read_unaligned`. I had no idea. That might be worth calling out in its documentation?

Note that the reference still needs to be `T`-aligned, as all references do. But it does not have to be `U`-aligned.

**Comment by newpavlov** [comment]
It was changed in rust-lang/rust#55052.
