### ISSUE TITLE
Forbid fabricating reference

### ISSUE THREAD

**Issue by sanxiyn** [nikomatsakis/rust-memory-model#22]
``` rust
fn f() -> i32 {
    let x = 1234;
    g();
    x
}
```

It is desirable to allow optimizing the above program such that 1234 is always returned and no memory store is made. (1234 can be directly loaded to register.) Looking at LLVM IR, Rust already performs such optimization.

C memory model allows this optimization. I think whatever Rust memory model we decide on should allow this optimization. But as I understand, strict interpretation of "pointers are just integers" does not allow this optimization. For example, `g()` can iterate from 0 to usize::MAX, casting integer to pointer, compare pointed value to 1234, and when it is 1234 replace it with 1235. In general, if pointers are just integers, `g()` can fabricate reference to `x`. Optimization is valid in C, because "pointer to x" cannot be fabricated from any integer, even the integer that has same value as "pointer to x".

[A Formal C Memory Model Supporting Integer-Pointer Casts](http://sf.snu.ac.kr/intptrcast/) (PLDI 2015) investigates this issue in detail.

**Comment by arielb1** [comment]
In detail? Every memory model that allows access to non-address-taken temps is worthless wrt. optimizing compilers. The interesting points come when Rust allows _temporary_ access to temps.

**Comment by RalfJung** [comment]
Stacked Borrows indeed allows that optimization, and I don't think anyone is proposing a model that would not allow this. Some more intricate examples are part of the Stacked Borrows test suite that we would also use to evaluate alternative models. Hence, closing for now.
