### ISSUE TITLE
Reordering writes to before external function calls

### ISSUE THREAD

**Issue by arielb1** [nikomatsakis/rust-memory-model#25]
Code example:

``` Rust
extern "C" {
    fn abort_if(condition: bool);
}

fn example(index: usize) {
    unsafe {
        let mut buf: [u8; 1024] = [0; 1024];
        abort_if(index >= 1024);
        *buf.get_unchecked_mut(index) = 0xff;
    }
}
```

This must call `abort_if` _before_ the `unchecked_get_mut` - i.e. if `abort_if` has the obvious implementation, this code must never be UB.

This seems obvious to me, but according to [some people](https://blogs.msdn.microsoft.com/oldnewthing/20140627-00/?p=633), doing the write first is Perfectly Legal because of UB.

**Comment by strega-nil** [comment]
> However, if any such execution contains an undefined operation, this International Standard places no requirement on the implementation executing that program with that input (not even with regard to operations preceding the first undefined operation).

The important thing is "if any such execution contains an undefined operation". No execution of the code given contains an undefined operation.
