### ISSUE TITLE
Legal values for a Box<T> where T is zero-sized

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/rust-memory-model#3]
On IRC, @mystor asked me whether, given some zero-sized type `ZST`, it would be legal to represent `Box<ZST>` using some arbitrary non-null value, or must it be a particular value (e.g., 1)?

For example, if there is a pointer `p` to some stack variable, can one write `unsafe { Box::from_raw(p as *mut ZST) }` and have that be a legal box?

**Comment by mystor** [comment]
If this is a legal box as well, is it safe to assume that the compiler will never decide to not propagate the given value, and just give 1 whenever asked for what the pointer value is for a boxed zero sized type?

**Comment by Amanieu** [comment]
I'm of the opinion that `Box::from_raw` should only ever be called with a pointer allocated by `Box::new`.

Conceptually, we are allocating a zero-sized block of memory (which may have malloc headers, so the real allocation may be bigger than zero), and we should use the same pointer value when we are freeing it.

The fact that `Box::new` currently always returns a pointer value of 1 is an implementation detail: it's just an optimization to avoid allocating zero-sized blocks of memory.

**Comment by arielb1** [comment]
My preference is that any non-null value is a valid pointer to a 0-sized type.

Also, for things to make sense, all reborrows would have to prefer that value, e.g.:

``` Rust
struct Foo((), ());

fn addr_of<T>(t: &T) -> usize { t as *const T as usize }
fn main() {
    let foo = unsafe { &*(0x1337 as *const Foo) };
    assert_eq!(addr_of(foo), 0x1337);
    assert_eq!(addr_of(&*foo), 0x1337);
    assert_eq!(addr_of(&foo.0), 0x1337);
    assert_eq!(addr_of(&foo.1), 0x1337);
}
```

**Comment by strega-nil** [comment]
@arielb1 I don't think so. `&foo` is it's own object, not a ZST.

edit: nvm :P

**Comment by arielb1** [comment]
Whatever is legal for `Box` is more of a library issue. I think programmers want to rely on `Box::<ZST>::new()` being copyable and being a "const fn".

**Comment by strega-nil** [comment]
@arielb1 I... don't know if I agree? I _think_ we should be able to say that `Box::<Zst>::new()` may allocate, just like `malloc(0)`. It might, for example, do some debug info thing.

**Comment by arielb1** [comment]
That would be a breaking change.

**Comment by strega-nil** [comment]
Is it? Do we ever say that we _won't_ allocate? I guess it is _literally_ a breaking change... but have we made promises in this area?

**Comment by arielb1** [comment]
A breaking change is a change that breaks user code. If we're going around making these kinds of breaking changes we might as well reverse struct drop order and be done with it.

**Comment by strega-nil** [comment]
@arielb1 well... I just need to write that RFC :)

**Comment by nikomatsakis** [comment]
So really there are two questions here that should be separated out. One is what is legal in terms of `Box<T>` (for any T, but especially ZST), and the other is what about pointers to unsized types. I am going to rename this issue heading to be specific to `Box<T>` and then open a second for the more general question, I guess. Then I'll give my two cents. =)

**Comment by nikomatsakis** [comment]
My feeling is that `Box` should be relatively transparent -- for example, I would tie its value specifically to the default allocator, and document the behavior for ZST. So, if the type is ZST, then we do not invoke `free` -- otherwise, the pointer can be any pointer which can legally be given to the default allocator to be freed (and which is not aliased).

This would mean that, for example, it may well be legal to take a `*T` from C which was allocated with malloc and convert it to a `Box`, as long as you know that the default allocator is C malloc. This seems like a useful bit of interop, if perhaps not the most recommended pattern (because it limits portability).

(Also, of course, if Box becomes customizable with respect to its allocator, then basically all of this logic still stands, but with respect to the allocator for that given box.)

**Comment by gnzlbg** [comment]
Should `read`ing from a pointer that is not properly aligned have an exception for ZSTs or should that be undefined behavior?

Depending on the answer to that question, `Box<T>` and `&T` might be able to take any non-zero values when `T` is a ZST, or they might only take certain values (multiples of the alignment).

FWIW the current implementation returns `mem::align_of::<T>()`, such that the pointer behind the Box is always properly aligned.

EDIT: @rkruppe mentioned `[T; 0]` and `#[repr(align(N))] struct T()` as ZSTs where the difference might matter.

---

Also related to https://github.com/nikomatsakis/rust-memory-model/issues/10

**Comment by RalfJung** [comment]
> Should reading from a pointer that is not properly aligned have an exception for ZSTs or should that be undefined behavior?

For references and `Box`, not just *reading* is UB when the pointer is unaligned. Even just *creating* an unaligned reference is UB. I see no reason why ZSTs should get an exception there? We still emit that annotation to LLVM and we still may want to do enum layout optimizations.

**Comment by gnzlbg** [comment]
That makes sense, for me that settles it. Is there a memory model document anywhere where these kind of things are actually written to?

**Comment by RalfJung** [comment]
No :(  We haven't really started writing down anything yet... or even found a good structure to put stuff in. I hope to be able to work on that some more this summer.

**Comment by RalfJung** [comment]
This is now being discussed as part of the validity invariants: https://github.com/rust-lang/unsafe-code-guidelines/issues/145.

**Comment by Lucretiel** [comment]
Er- it looks like the linked thread doesn't talk at all about Boxing ZSTs, unless I'm missing something?
