### ISSUE TITLE
Request: Weekly Summary Mail List?

### ISSUE THREAD

**Issue by naftulikay** [nikomatsakis/rust-memory-model#49]
I find all of the work being done here really fascinating. As I'm sure everyone is, I'm very busy and it's difficult for me to tightly watch everything going on.

Is there any way we as the community could have recurrent (weekly? monthly?) updates on progress, maybe in the form of a mailing list or an article linked by "This Week in Rust?"

Thanks so much for doing what you're doing!

**Comment by RalfJung** [comment]
This effort moved to https://github.com/rust-lang/unsafe-code-guidelines, where the plan is to slowly build up [a document](https://rust-lang.github.io/unsafe-code-guidelines/) with the results of our discussions, and to make public announcements each time we got through "a chapter".

At our current rate of progress, weekly updates would not say much ;) but feel free to re-open this issue over there.
