### ISSUE TITLE
Breaking changes we want to make

### ISSUE THREAD

**Issue by arielb1** [nikomatsakis/rust-memory-model#9]
What kinds of currently-working semantics are we OK with breaking?

**Comment by arielb1** [comment]
## Description

Dropping a value of type  `Box<ZST>` twice, where `ZST` is a zero-sized type,

## Reason for breakage

We may want to add debuginfo for all allocations.

## Example that will become UB

``` Rust
fn main() {
    let mut b = Box::new(());
    drop(unsafe { Box::from_raw(&mut *b) });
    drop(unsafe { Box::from_raw(&mut *b) });
}
```

This is more of a library issue, but I am afraid people are already abusing it.

**Comment by Amanieu** [comment]
# Description

1) The ordering of fields in a non-repr(C) struct may change.

2) We may want to exclude alignment padding from the size of a type (https://github.com/rust-lang/rfcs/issues/1397)

# Reason for breakage

Better struct packing, lower cache usage.

# Problems

1) This will break any code that makes assumptions about the layout of non-repr(C) types.

2) This will break code that overwrite a value by writing to `mem::size_of::<T>` bytes. As far as I know the only affected crate is [atomic-rs](https://github.com/Amanieu/atomic-rs), which needs to use `mem::size_of_inner::<T>` instead.

**Comment by strega-nil** [comment]
@Amanieu number 2 is unlikely to change, afaik. It would result in slower, more complicated code. However, it is possible.

**Comment by nikomatsakis** [comment]
I feel like collecting these in a single issue will quickly become annoying. I propose that we create a tag ("proposed-breaking-change") and then just create issues for each of them.

**Comment by RalfJung** [comment]
Closing for now. non-repr(C) field order has indeed changed; for the "tail padding" of a type see https://github.com/rust-lang/unsafe-code-guidelines/issues/176 and https://github.com/rust-lang/unsafe-code-guidelines/issues/306; and the `Box` change should probably have its own thread if someone wants to pursue this.
